// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const SUPABASE_URL = "https://kyophsvsoriguqijlutr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt5b3Boc3Zzb3JpZ3VxaWpsdXRyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg0OTc2NTgsImV4cCI6MjA2NDA3MzY1OH0.FLRQ8uo3vrDEwyFv_teRmhv-FiIkUJHNx7uAb62f4Ik";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY
);
